FROM centos:centos8

# reminder, use {} around environmental variables, otherwise docker uses it as a literal

LABEL edu.mda.bcb.name="MetaBatch Analyzer: GDCDownload" \
      edu.mda.bcb.sub="gdc" \
      edu.mda.bcb.gdc.version="BEA_VERSION_TIMESTAMP" \
      edu.mda.bcb.gdc.log="<LOG_DIR>" \
      edu.mda.bcb.gdc.start="<START_SCRIPT>" \
      edu.mda.bcb.gdc.stop="<STOP_SCRIPT>" \
      edu.mda.bcb.gdc.upcheck="<UPCHECK_SCRIPT>"

# Use Java 8, still supported, and all the tools depend on it -- simplifies other installs and maintenance
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel java-1.8.0-openjdk-headless && \
    update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64/jre/bin/java 1 && \
    update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64/bin/javac 1 && \
    update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64/bin/jar 1 && \
    update-alternatives --install /usr/bin/javah javah /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64/bin/javah 1 && \
    echo "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64" >> /etc/profile.d/java.sh && \
    yum update -y && \
    yum clean all

# create and setup bcbuser
# also, set permissions and ownerships on internal docker directories
RUN useradd -l -s /bin/bash -d /home/bcbuser -u <USERID> bcbuser && \
    chown -R bcbuser:bcbuser /home/bcbuser

# make subdirectory in user home for running
# COPY is always done as root!!!!
RUN mkdir /home/bcbuser/gdcdownload && \
    chown -R bcbuser:bcbuser /home/bcbuser/gdcdownload && \
    chmod -R u+rwx /home/bcbuser/gdcdownload
COPY installations /home/bcbuser/gdcdownload
RUN chown -R bcbuser:bcbuser /home/bcbuser/gdcdownload && \
    chmod -R u+rwx /home/bcbuser/gdcdownload

# switch from root to bcbuser user
USER bcbuser

# set working directory for future commands
WORKDIR /home/bcbuser/gdcdownload

# start this image with this command, which runs GDCDownload every 2 minutes
# docs for arguments to CMD runGDCDownload.bash, below
# first argument, URL for mbaService (see docker-compose file for service declaration) port is internal port declared in docker-compose
# second argument, anything but 'once' means repeat forever
CMD ["/bin/bash", "/home/bcbuser/gdcdownload/runGDCDownload.bash", "http://mbaService:8080", "forever"]

