FROM mdabcb/mbatchsa_image:HUB_BEA_VERSION_TIMESTAMP
# CI/CD replaces above with local repo image

# reminder, use {} around environmental variables, otherwise docker uses it as a literal

LABEL edu.mda.bcb.name="MetaBatch Analyzer: MBatch" \
      edu.mda.bcb.sub="mba" \
      edu.mda.bcb.bea.version="BEA_VERSION_TIMESTAMP" \
      edu.mda.bcb.bea.log="<LOG_DIR>" \
      edu.mda.bcb.bea.start="<START_SCRIPT>" \
      edu.mda.bcb.bea.stop="<STOP_SCRIPT>" \
      edu.mda.bcb.bea.upcheck="<UPCHECK_SCRIPT>"

# create and setup mbauser use to external directory owner
# also, set permissions and ownerships on internal docker directories
# group already exists groupadd -g <GROUPID> mbagroup && \
RUN useradd -l -s /bin/bash -d /home/mbauser -u <USERID> -g <GROUPID> mbauser && \
    chown -R mbauser:bcbgroup /home/mbauser && \
    chmod -R 777 /home/mbauser

# make subdirectory in user home for running
RUN mkdir /home/mbauser/mbatch && \
    chown -R mbauser:bcbgroup /home/mbauser/mbatch && \
    chmod -R u+rwx /home/mbauser/mbatch
COPY --chown=mbauser:bcbgroup --chmod=775 installations /home/mbauser/mbatch

# switch from root to mbauser user
USER mbauser

# set working directory for future commands
WORKDIR /home/mbauser/mbatch
CMD /home/mbauser/mbatch/runRproc.bash http://mbaService:8080/

